logging:
  level:
    com.robertoman.sproxy: debug

config:
  #############################
  ############ TLS ############ --> THIS FEATURE IS STILL NOT AVAILABLE
  #############################
  tls:
    enabled: false

  #####################################
  ############ SProxy MODS ############
  #####################################
  mod:
    ########################
    ## SProxy mod HEADERS ##
    ########################
    # From here it is possible to modify both request and response headers (regex based)
    headers:
      enabled: true
      request:
        allow-overrides: false
        map:
          # example: (please note -> the indentation is important, here's we are declaring a Map<String, List<String>>)
          '[(https?://)?postman-echo.com/.*+]':
                                              - 'Foo: bar'
      response:
        allow-overrides: false
        map:
          # example: (please note -> the indentation is important, here's we are declaring a Map<String, List<String>>)
          '[(https?://)?postman-echo.com/.*+]':
                                              - 'Access-Control-Allow-Origin: *'

    #########################
    ## SProxy mod SECURITY ## --> THIS MOD IS STILL NOT AVAILABLE
    #########################
    # If this mod is enabled you need to login calling the /login endpoint in order to get a SProxy-Bearer
    # to use for Bearer Authentication
    security:
      enabled: false
      username: username
      password: password
      methods: "POST,HEAD,GET"
      keystore:
        zip:
          path: /home/roberto/keystore/keystore.zip

    ####################
    ## SProxy mod URL ##
    ####################
    # From here it is possible to write a whitelist url that SProxy will be authorized to call (regex based)
    url:
      enabled: false
      whitelist:
        - '(https?://)?postman-echo.com/.*+'
      blacklist:
        - '(https?://)?www.google.com'

    ####################
    ## SProxy mod WAF ##  --> THIS MOD IS IN AN EXPERIMENTAL STATE
    ####################
    waf:
      enabled: false
      allows:
        backslash: false
        url-encoded-double-slash: true
        url-uncoded-percent: false
        url-encoded-period: false
        url-encoded-slash: false
        semicolon: false
        http-methods:
          - GET
          - HEAD