spring:
  output:
    ansi:
      enabled: ALWAYS
  banner:
    image:
      invert: false



# TUNNELING-PROXY ENVIRONMENT PROFILE CONFIGS
---
spring:
  profiles: tunneling-proxy

config:
  security:
    enabled: false
    username: user
    password: pass
    http-methods:
      - HEAD
      - POST
