server:
  port: 4321

spring:
  application:
    name: sproxy
  output:
    ansi:
      enabled: ALWAYS
  banner:
    image:
      invert: false

logging:
  level:
    root: info
    com.robertoman.sproxy: debug
    com.github.robertomanfreda.java.jwt: debug
  file:
    name: target/${spring.application.name}


# TUNNELING-PROXY ENVIRONMENT PROFILE
---
spring:
  profiles: sproxy

config:
  security:
    enabled: false
    username: username
    password: password
    # The POST method is required in order to complete the login process. If not specified it will be automatically added by SProxy.
    methods: "POST,HEAD,GET"
    keystore:
      zip:
        path: /home/roberto/keystore/keystore.zip
  cors:
    enabled: false
    rules: >
      <PATTERN>(https?://)?postman-echo.com/.*+</PATTERN><VALUE>*</VALUE>,
      <PATTERN>(https?://)?www.google.com/.*+</PATTERN><VALUE>*</VALUE>
  filtering:
    enabled: false
    rules: >
      <PATTERN>(https?://)?postman-echo.com/.*+</PATTERN>,
      <PATTERN>(https?://)?www.google.com/.*+</PATTERN>