name: Java CI with Maven

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push image
        run: |
          IMAGE_ID="robertoman/sproxy"
          VERSION="lastest"
          TAG="$IMAGE_ID$VERSION"
          echo $TAG
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
